name: Continuous Integration

on:
  workflow_dispatch:
  # pull_request:
    # types: [opened, synchronize, reopened, ready_for_review]
    # paths:
    #   - "packages/**"
    #   - 'package.json'
    #   - 'pnpm-lock.yaml'
    #   - '.github/workflows/ci.yml'
    # branches: 
    #   - main
    #   - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test-coverage:
    name: Continuous Integration
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test:run