name: Publish Develop to Pkg-Pr-New
on:
  push:
    paths:
      - "packages/**"
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "packages/**"
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies=false

      - name: Build
        run: |
          cd packages/scan
          NODE_ENV=production pnpm build
        env:
          NODE_ENV: production

      - name: Publish NPM Package to pkg-pr-new
        run: pnpx pkg-pr-new publish ./packages/scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}